[project]
name = "arxiv-deep-research-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ijson>=3.3.0",
    "openai>=1.73.0",
    "pandas>=2.2.3",
]
